# DO NOT EDIT. Generated by node/scripts/generate-payment-deployments.mjs
import json
SOLANA_V14_DEPLOYMENTS = json.loads(r'''{
  "devnet": {
    "network": "devnet",
    "environment": "dev",
    "splitterVersion": "1.4",
    "status": "disabled",
    "settlementEnabled": false,
    "disabledReason": "Backend Solana receipt verification is not implemented",
    "programId": "8dty5bD738Z9TzEkDu8vLSnhpJNWtEGMUEcYaKCUTY6y",
    "idl": {
      "name": "splitter",
      "version": "1.4.1",
      "artifact": "deployments/splitter_v14/splitter.devnet.json",
      "sha256": "75a0419e6f2a2dd20e2345dfd7b027bcbcd0be2bcd02cd108f6bda8d8c4035f2"
    }
  },
  "mainnet": {
    "network": "mainnet",
    "environment": "prod",
    "splitterVersion": "1.4",
    "status": "disabled",
    "settlementEnabled": false,
    "disabledReason": "Backend Solana receipt verification is not implemented and upgrade authority is not multisig",
    "programId": "724Ut31i4ecY4dJ25z8HuZetu3A43xtNkPdk4JdbsfdD",
    "idl": {
      "name": "splitter",
      "version": "1.4.1",
      "artifact": "deployments/splitter_v14/splitter.mainnet.json",
      "sha256": "d7890e226fc27d4d54801b9b208c44851567578793ff1855a007395f420ebee2"
    }
  }
}''')
